Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Console-Kernel.html"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Aschedule\u0028\u0029",
            "name": "schedule",
            "summary": "Define\u0020the\u0020application\u0027s\u0020command\u0020schedule.",
            "url": "classes/App-Console-Kernel.html#method_schedule"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Acommands\u0028\u0029",
            "name": "commands",
            "summary": "Register\u0020the\u0020commands\u0020for\u0020the\u0020application.",
            "url": "classes/App-Console-Kernel.html#method_commands"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/App-Exceptions-Handler.html"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020exception\u0020handling\u0020callbacks\u0020for\u0020the\u0020application.",
            "url": "classes/App-Exceptions-Handler.html#method_register"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024levels",
            "name": "levels",
            "summary": "A\u0020list\u0020of\u0020exception\u0020types\u0020with\u0020their\u0020corresponding\u0020custom\u0020log\u0020levels.",
            "url": "classes/App-Exceptions-Handler.html#property_levels"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontReport",
            "name": "dontReport",
            "summary": "A\u0020list\u0020of\u0020the\u0020exception\u0020types\u0020that\u0020are\u0020not\u0020reported.",
            "url": "classes/App-Exceptions-Handler.html#property_dontReport"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontFlash",
            "name": "dontFlash",
            "summary": "A\u0020list\u0020of\u0020the\u0020inputs\u0020that\u0020are\u0020never\u0020flashed\u0020to\u0020the\u0020session\u0020on\u0020validation\u0020exceptions.",
            "url": "classes/App-Exceptions-Handler.html#property_dontFlash"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController",
            "name": "ClientsController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Alist_clients\u0028\u0029",
            "name": "list_clients",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_list_clients"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Asearcher_client\u0028\u0029",
            "name": "searcher_client",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_searcher_client"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Adel_client\u0028\u0029",
            "name": "del_client",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_del_client"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Aget_client_info\u0028\u0029",
            "name": "get_client_info",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_get_client_info"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Aapply_form\u0028\u0029",
            "name": "apply_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_apply_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Ashow_form\u0028\u0029",
            "name": "show_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_show_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Afedit_client\u0028\u0029",
            "name": "fedit_client",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_fedit_client"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClientsController\u003A\u003Aedit_client\u0028\u0029",
            "name": "edit_client",
            "summary": "",
            "url": "classes/App-Http-Controllers-ClientsController.html#method_edit_client"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController",
            "name": "ManagersController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Alist_managers\u0028\u0029",
            "name": "list_managers",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_list_managers"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Asearch_manager\u0028\u0029",
            "name": "search_manager",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_search_manager"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Adel_manager\u0028\u0029",
            "name": "del_manager",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_del_manager"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Aget_manager_info\u0028\u0029",
            "name": "get_manager_info",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_get_manager_info"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Aapply_form\u0028\u0029",
            "name": "apply_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_apply_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Ashow_form\u0028\u0029",
            "name": "show_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_show_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Afedit_manager\u0028\u0029",
            "name": "fedit_manager",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_fedit_manager"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Aedit_manager\u0028\u0029",
            "name": "edit_manager",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_edit_manager"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Acontrol_panel\u0028\u0029",
            "name": "control_panel",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_control_panel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ManagersController\u003A\u003Awidget_calendar\u0028\u0029",
            "name": "widget_calendar",
            "summary": "",
            "url": "classes/App-Http-Controllers-ManagersController.html#method_widget_calendar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController",
            "name": "MyAuthController",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Aplogin\u0028\u0029",
            "name": "plogin",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_plogin"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Apregister\u0028\u0029",
            "name": "pregister",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_pregister"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003Adashboard\u0028\u0029",
            "name": "dashboard",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_dashboard"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\MyAuthController\u003A\u003AsignOut\u0028\u0029",
            "name": "signOut",
            "summary": "",
            "url": "classes/App-Http-Controllers-MyAuthController.html#method_signOut"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController",
            "name": "TasksController",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Alist_tasks\u0028\u0029",
            "name": "list_tasks",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_list_tasks"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Asearcher_task\u0028\u0029",
            "name": "searcher_task",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_searcher_task"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Adel_task\u0028\u0029",
            "name": "del_task",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_del_task"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Aget_task_info\u0028\u0029",
            "name": "get_task_info",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_get_task_info"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Aapply_form\u0028\u0029",
            "name": "apply_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_apply_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Ashow_form\u0028\u0029",
            "name": "show_form",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_show_form"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Afedit_task\u0028\u0029",
            "name": "fedit_task",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_fedit_task"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TasksController\u003A\u003Aedit_task\u0028\u0029",
            "name": "edit_task",
            "summary": "",
            "url": "classes/App-Http-Controllers-TasksController.html#method_edit_task"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024routeMiddleware",
            "name": "routeMiddleware",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware.",
            "url": "classes/App-Http-Kernel.html#property_routeMiddleware"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ValidateSignature",
            "name": "ValidateSignature",
            "summary": "",
            "url": "classes/App-Http-Middleware-ValidateSignature.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ValidateSignature\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020query\u0020string\u0020parameters\u0020that\u0020should\u0020be\u0020ignored.",
            "url": "classes/App-Http-Middleware-ValidateSignature.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Models\\Client",
            "name": "Client",
            "summary": "Class\u0020Client",
            "url": "classes/App-Models-Client.html"
        },                {
            "fqsen": "\\App\\Models\\Client\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Client.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Manager",
            "name": "Manager",
            "summary": "",
            "url": "classes/App-Models-Manager.html"
        },                {
            "fqsen": "\\App\\Models\\Manager\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Manager.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Task",
            "name": "Task",
            "summary": "",
            "url": "classes/App-Models-Task.html"
        },                {
            "fqsen": "\\App\\Models\\Task\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Task.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\weekOfMonth\u0028\u0029",
            "name": "weekOfMonth",
            "summary": "",
            "url": "namespaces/default.html#function_weekOfMonth"
        },                {
            "fqsen": "\\getWeekday\u0028\u0029",
            "name": "getWeekday",
            "summary": "",
            "url": "namespaces/default.html#function_getWeekday"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar",
            "name": "WidgetCalendar",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#method___construct"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003Ayear_addFromDb\u0028\u0029",
            "name": "year_addFromDb",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#method_year_addFromDb"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003Ayear_calendar\u0028\u0029",
            "name": "year_calendar",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#method_year_calendar"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003Ayear_empty_row\u0028\u0029",
            "name": "year_empty_row",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#method_year_empty_row"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003Awidget\u0028\u0029",
            "name": "widget",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#method_widget"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024cal",
            "name": "cal",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_cal"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024year",
            "name": "year",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_year"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024records",
            "name": "records",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_records"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024date_field",
            "name": "date_field",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_date_field"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024cap_field",
            "name": "cap_field",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_cap_field"
        },                {
            "fqsen": "\\App\\Other\\WidgetCalendar\u003A\u003A\u0024link",
            "name": "link",
            "summary": "",
            "url": "classes/App-Other-WidgetCalendar.html#property_link"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider",
            "name": "AuthServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AuthServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020authentication\u0020\/\u0020authorization\u0020services.",
            "url": "classes/App-Providers-AuthServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "The\u0020model\u0020to\u0020policy\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-AuthServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider",
            "name": "BroadcastServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-BroadcastServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-BroadcastServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003AshouldDiscoverEvents\u0028\u0029",
            "name": "shouldDiscoverEvents",
            "summary": "Determine\u0020if\u0020events\u0020and\u0020listeners\u0020should\u0020be\u0020automatically\u0020discovered.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_shouldDiscoverEvents"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "The\u0020event\u0020to\u0020listener\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider",
            "name": "RouteServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-RouteServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Define\u0020your\u0020route\u0020model\u0020bindings,\u0020pattern\u0020filters,\u0020and\u0020other\u0020route\u0020configuration.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AconfigureRateLimiting\u0028\u0029",
            "name": "configureRateLimiting",
            "summary": "Configure\u0020the\u0020rate\u0020limiters\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_configureRateLimiting"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AHOME",
            "name": "HOME",
            "summary": "The\u0020path\u0020to\u0020the\u0020\u0022home\u0022\u0020route\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#constant_HOME"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Other",
            "name": "Other",
            "summary": "",
            "url": "namespaces/app-other.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        }            ]
);
